### ISSUE TITLE
Fix Utilities.fetchData() 

### ISSUE THREAD

**Issue by nku-bsw** [bruegmann/blue-react#11]
Got an Error when i added a new BlueReactPage.tsx.
 Error:
 Property 'fetchData' does not exist on type '{ hasClass: (el: any, className: any) => any; addClass: (el: any, className: any) => void; removeClass: (el: any, className: any) => void; toggleClass: (element: any, className: any) => void; ... 11 more ...; registerFluentBtns: null; }'.

**Comment by lgk-bsw** [comment]
Only occurs inside the blue-react project itself when using the untyped `Utilities` class from `src`.
As a workaround, use the productive version of `Utilities` from `dist/components`:

```js
import { Utilities } from "../../../index";
```
