### ISSUE TITLE
Layout Movement for long Sub-MenuItems

### ISSUE THREAD

**Issue by bri-bsw** [bruegmann/blue-react#115]
If a sub menu item is longer than the main menu item, the menu moves.
![image](https://user-images.githubusercontent.com/67693818/201680156-108d628b-f5ff-4037-8b30-93e394825fc1.png)

![image](https://user-images.githubusercontent.com/67693818/201680218-9f510fde-6f46-4ead-bdbd-b16df7a58bf4.png)

**Comment by lgk-bsw** [comment]
You can easily solve this setting the dropdown menu's position to `absolute` and set the `right` property to `0`.

Example by using Bootstrap's Utility classes:
```jsx
<ActionMenu>
    <MenuItem
        icon={<Pencil className="bi" />}
        iconForActive={<PencilFill className="bi" />}
        label="Edit"
        onClick={toggleEdit}
        isActive={edit}
    />

    <div>
        <MenuItem
            label="Actions"
            supportOutside
            dropdownClassName="position-absolute end-0"
        >
            <MenuItem label="Do a lot, a loooot of stuff" />
            <MenuItem label="Yeah, really a lot of stuff" />
        </MenuItem>
    </div>
</ActionMenu>
```
Live demo: https://bruegmann.github.io/blue-react/v8/demo#record
Code: https://github.com/bruegmann/blue-react/blob/master/src/docs/components/DemoApp.tsx#L228
